### ISSUE TITLE
Idea: Broken path detector

### ISSUE THREAD

**Issue by originalfoo** [krzychu124/BrokenNodeDetector#11]
For building problems that require visit from service vehicle (eg. dead people needing hearse) would it be possible to check paths for all related service buildings?

User could select option via the mod panel then click a building that has problem, and it could try and path relevant (to the problem the building has) service vehicle from each applicable service building, and indicate which can't reach the building.

This way user might be able to get some indication of where problem might be.

**Comment by krzychu124** [comment]
I would do it the other way. If you see a building that has flickering vehicle number you could select it and BND could show a small popup with list of buildings that cannot be reached (vehicle despawns after searching for path to target). List with buttons to move camera there. It will be much easier to implement since the only thing I need is a field paths monitor + ui

**Comment by originalfoo** [comment]
That would be fantastic!

**Comment by krzychu124** [comment]
@aubergine10, @chameleon-tbn any suggestions?🙃 

https://user-images.githubusercontent.com/19638970/167055739-5a74b063-3153-4dcb-b022-33da79847c0b.mp4

**Comment by originalfoo** [comment]
> any suggestions?

Release to workshop :)

**Comment by chameleon-tbn** [comment]
I Like @aubergine10 s Suggestion :)

Looks good, i need it!

**Comment by krzychu124** [comment]
Ok, I think I'll try to add EML integration since I'm touching props so tools won't work correctly (if not spam the log with exceptions).

I still have to fix memory leaks 😂 Generating dynamic UI from templates requires a bit more attention and also iterators (`StartCoroutine()` + `IEnumerator/IEnumerator<T>`) are annoying - they seem to swallow exceptions so without debugger attached I don't even see that something went wrong besides partially rendered or no UI 😬
